name: AuthBB
version: '1.1'
main: io.github.altkat.authBB.AuthBB
api-version: '1.21'
author: AltKat(StreetMelodeez)
softdepend:
  - AuthMe
commands:
  authbb:
    description: general command
    usage: /authbb
    aliases:
      - authbossbar
  server:
    description: Sends to lobby server.
    usage: /server servername
    permission: AuthBB.server
  send:
    description: Sends players to lobby server.
    usage: /send player server
    permission: AuthBB.send
